# Auto-provisioned Prometheus datasource
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_ds
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
      timeInterval: 15s
      exemplarTraceIdDestinations: []
    secureJsonData: {}
